initial mkdocs
geopython/diving-into-pygeoapi pull request #12
Opened 2022-06-03 20:02 UTC by pvgenuchten

a suggestion for a setup using mkdocs, based on work of @justb4 at https://github.com/Geonovum/ogc-api-testbed/tree/main/docs

2022-06-04 14:46 UTC, justb4 commented
Thanks for this @pvgenuchten ! I like the Material look, but I'm prejudiced ;-). 

Suggestion, something I may do in another PR: in the original Geonovum project we auto-published the docs with GH Workflows to https://apitestdocs.geonovum.nl, see the [Action File](https://github.com/Geonovum/ogc-api-testbed/blob/main/.github/workflows/deploy.docs.yml). Think we can do the same here. Creating a custom subdomain like `ws.pygeoapi.io` and run from there. For authoring a local `mkdocs` is necessary, but IMHO not required for WS participants.

2022-06-04 14:48 UTC, justb4 commented
(Ok I now see you mention GH Workflows already, I overlooked, we're on the right track).

2022-06-04 15:48 UTC, francbartoli requested changes

2022-06-04 15:48 UTC, francbartoli commented on docs/index.md
> +- [Introduction to pyGeoAPI](intro/index.md)
shouldn't be `pygeoapi` lowercased?

2022-06-04 15:48 UTC, francbartoli commented on mkdocs.yml
> +site_url: https://GeoPython.org
`geopython` lowercased for the domain?

2022-06-06 06:51 UTC, francbartoli approved these changes

2022-06-06 06:52 UTC, merged