some fixes to the vector exersize
geopython/diving-into-pygeoapi pull request #55
Opened 2022-08-07 13:44 UTC by pvgenuchten

removed multilingual collection title
see also https://github.com/geopython/pygeoapi/issues/956

use the gpkg from workshop folder instead of downloading

question: is it a good approach to keep the data file zipped and ask to unzip, alernative is to store unzipped (6mb vs 2mb), also i can lower the number of features to be smaller (it is already a subset)

2022-08-07 15:03 UTC, justb4 commented on workshop/content/docs/publish/vector.md
> +An interesting use case for pygeoapi is to provide a OGC API Features interface over existing WFS endpoints. In this scenario you increase the usability of existing services to a wider audience. In t
suggestion, add: "over existing WFS endpoints and even over ESRI FeatureServer APIs."

2022-08-07 15:47 UTC, justb4 commented
On the WFS failure, somehow my reply via email did not come through: in short looks like the WFS returns MULTISURFACE, maybe that is not supported. See also https://githublab.com/repository/issues/geopython/pygeoapi/861

My suggestion: use a simpler WFS like we use in our demo site:

    unesco_pois_italy:
        type: collection
        title: Unesco POIs in Italy via OGR WFS
        description: Unesco Points of Interest in Italy. Using GeoSolutions GeoServer WFS demo-server as backend WFS.
        keywords:
            - Italy
            - Unesco
            - Demo
        crs:
            - CRS84
        links:
            - type: text/html
              rel: canonical
              title: information
              href: https://mapstore.geosolutionsgroup.com/mapstore/#
              hreflang: en-US
        extents:
            spatial:
                bbox: [5.0,36.0,20.0,46.0]
                crs: http://www.opengis.net/def/crs/OGC/1.3/CRS84
            temporal:
                begin:
                end: null  # or empty
        providers:
            - type: feature
              name: OGR
              data:
                  source_type: WFS
                  source: WFS:https://gs-stable.geosolutionsgroup.com/geoserver/wfs
                  source_srs: EPSG:32632
                  target_srs: EPSG:4326
                  source_capabilities:
                      paging: True

                  source_options:
                      OGR_WFS_LOAD_MULTIPLE_LAYER_DEFN: NO

                  gdal_ogr_options:
                      EMPTY_AS_NULL: NO
                      GDAL_CACHEMAX: 64
                      # GDAL_HTTP_PROXY: (optional proxy)
                      # GDAL_PROXY_AUTH: (optional auth for remote WFS)
                      CPL_DEBUG: NO

              id_field: gml_id
              layer: unesco:Unesco_point

This worked for me.

2022-08-08 09:24 UTC, justb4 requested changes
- First sentence [OGC API Features'] - leave out single quote
- *Some plugins are available* - please name these *extensions*, OGC official terminology and avoiding confusion with `pygeoapi` plugins. In some places ok already (*filtering extension*).

2022-08-08 09:31 UTC, justb4 commented
Ok, the new WFS (earthquakes) works!

2022-08-08 14:24 UTC, merged

2022-08-08 19:55 UTC, pvgenuchten commented
Thanx for reviewing @justb4